logging.level.com.jaeyeonling: DEBUG

spring:
  application:
    name: stage1-faq-chatbot
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.1
      embedding:
        options:
          model: text-embedding-3-small

# 데이터 경로
faq:
  data-dir: ../data/layer1_faq
